<?php
$navData = array (
			'feeds'=>'我的讨论',
		  	  'feeds_option'=>array(
		    	'0'=>array(
		    		'feeds_subject'=>'我的通知',
		    		'feeds_content'=>array(
		    			'0'=>array(
		    				'icon'=>'icon-bell',
		    				'brief'=>'来通知啦测试哦',
		    				'time_stamp'=>'24小时前'
		    			),
		    			'1'=>array(
		    				'icon'=>'icon-bolt',
		    				'brief'=>'来闪电啦测试哦',	
		    				'time_stamp'=>'1分钟前'
		    			),
		    			'2'=>array(
							'icon'=>'icon-bullhorn',
							'brief'=>'来广播啦测试哦',
							'time_stamp'=>'刚刚'
		    			),
		    			'3'=>array(
		    				'icon'=>'icon-bullhorn',
							'brief'=>'来广播啦测试哦2',
							'time_stamp'=>'15分钟前'
		    			),
		    		)
		    	),
		    	'1'=>array(
		    		'feeds_subject'=>'未审批通知',
		    		'feeds_content'=>array(
		    			'0'=>array(
		    				'icon'=>'icon-bell',
		    				'brief'=>'来通知啦测试哦',
		    				'time_stamp'=>'24小时前'
		    			),
		    			'1'=>array(
		    				'icon'=>'icon-bolt',
		    				'brief'=>'来闪电啦测试哦',	
		    				'time_stamp'=>'1分钟前'
		    			),
		    			'2'=>array(
							'icon'=>'icon-bullhorn',
							'brief'=>'来广播啦测试哦',
							'time_stamp'=>'刚刚'
		    			),
		    			'3'=>array(
		    				'icon'=>'icon-bullhorn',
							'brief'=>'来广播啦测试哦2',
							'time_stamp'=>'15分钟前'
		    			),
		    		)
		    	),
		    	'2'=>array(
		    		'feeds_subject'=>'来电通知',
		    		'feeds_content'=>array(
		    			'0'=>array(
		    				'icon'=>'icon-bell',
		    				'brief'=>'来通知啦测试哦',
		    				'time_stamp'=>'24小时前'
		    			),
		    			'1'=>array(
		    				'icon'=>'icon-bolt',
		    				'brief'=>'来闪电啦测试哦',	
		    				'time_stamp'=>'1分钟前'
		    			),
		    			'2'=>array(
							'icon'=>'icon-bullhorn',
							'brief'=>'来广播啦测试哦',
							'time_stamp'=>'刚刚'
		    			),
		    			'3'=>array(
		    				'icon'=>'icon-bullhorn',
							'brief'=>'来广播啦测试哦2',
							'time_stamp'=>'15分钟前'
		    			),
		    		)
		    	),
		    ),
				
		);
$data =  json_encode($navData);
	echo $data;
?>