<?php
	$navdata = array(
//		'menu_data'=>
//			array(
			'0'=>array(
				'name'=>'日常办公',
				'icon_tag'=>'icon-book',
				'menu'=>array(
					'0'=>array(
						'directory'=>"work/work_record_index.html",
						'id'=>50,
						'name'=>'工作记录',
						'module_name'=>'setting_user_index',
					),
					'1'=>array(
						
						'directory'=>'work/work_check_index.html',
						'id'=>32,
						'name'=>'工作考核',
						'module_name'=>'setting_user_index',
					)
				)
			),
			'1'=>array(
				'name'=>'行政管理',
				'icon_tag'=>'icon-cogs',
				'menu'=>array(
					'0'=>array(
						'id'=>4,
						'directory'=>'administrative_approach.html',
						'name'=>'制度办法',
						'module_name'=>'setting_user_index',
					),
					'1'=>array(
						'id'=>5,
						'directory'=>'administrative_hr_index.html',
						'name'=>'人力资源',
						'module_name'=>'setting_user_index',
					),
					'2'=>array(
						'id'=>6,
						'directory'=>'administrative_access.html',
						'name'=>'考核管理',
						'module_name'=>'setting_user_index',
					),
				),
			),
			'2'=>array(
				'name'=>'客户管理',
				'icon_tag'=>'icon-group',
				'menu'=>array(
					'0'=>array(
						'id'=>14,
						'directory'=>'setting/setting_user_index.html',
						'name'=>'我的客户',
						'module_name'=>'setting_user_index',
					),
					'1'=>array(
						'id'=>15,
						'directory'=>'customer/customer_index.html',
						'name'=>'客户管理',
						'module_name'=>'setting_user_index',
					),
				)
			),
			'3'=>array(
				'name'=>'过程管理',
				'icon_tag'=>'icon-tasks',
				'menu'=>array(
					'0'=>array(
						'id'=>16,
						'directory'=>'process/process_index.html',
						'name'=>'客户过程管理',
						'module_name'=>'setting_user_index',
					),
					'1'=>array(
						'id'=>17,
						'directory'=>'customer/customer_index.html',
						'name'=>'银行过程管理',
						'module_name'=>'setting_user_index',
					),
				)
			),
			'4'=>array(
				'name'=>'系统设置',
				'icon_tag'=>'icon-cog',
				'menu'=>array(
					'0'=>array(
						'id'=>2,
						'directory'=>'Set/',
						'name'=>'用户设置',
						'module_name'=>'set_user',
					),
					'1'=>array(
						'id'=>8,
						'directory'=>'Set/',
						'name'=>'部门设置',
						'module_name'=>'set_dept',
					),
					'2'=>array(
						'id'=>9,
						'directory'=>'setting_role_index.html',
						'name'=>'角色权限管理',
						'module_name'=>'setting_user_index',
					),
				)
			),
			'5'=>array(
				'name'=>'数字台帐管理',
				'icon_tag'=>'icon-cog',
				'menu'=>array(
					'0'=>array(
						'id'=>12,
						'directory'=>'DigiM/',
						'name'=>'采购',
						'module_name'=>'purchase',
					),
					'1'=>array(
						'id'=>18,
						'directory'=>'DigiM/',
						'name'=>'入库',
						'module_name'=>'stock',
					),
					'2'=>array(
						'id'=>19,
						'directory'=>'DigiM/',
						'name'=>'台账',
						'module_name'=>'debit',
					),
					'3'=>array(
						'id'=>29,
						'directory'=>'DigiM',
						'name'=>'管理后台',
						'module_name'=>'admin',
					),
				)
			),
			

		//)
	);
	$data =  json_encode($navdata);
	echo $data;
	
?>